### esp file
esphome:
  name: name-plate

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Name-Plate Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# mqtt setup
mqtt:
  broker: 192.168.1.200
  username: homeassistant
  password: !secret mqtt_password

# subscribe to topic published
sensor:
  - platform: mqtt_subscribe
    name: "Data from topic"
    id: mysensor # test
    topic: the/topic # test

# Example configuration entry
font:
  - file: 'fonts/OpenSans-Regular.ttf'
    id: font1
    size: 8

spi:
  clk_pin: D0 #CLK
  mosi_pin: D1 #DIN

display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D6 #D3 #D6
    busy_pin: D7 #D2 #D1
    reset_pin: D5
    model: 2.90in
    full_update_every: 30
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");
      it.printf(0, 0, id(font1), "The data is: %s", id(mysensor).state.c_str()); # test