esphome:
  name: name-plate-1
  # on_boot:
  #   priority: -100
  #   then:
  #     # - display.page.show: page2
  #     - component.update: my_display

esp8266:
  board: d1_mini

substitutions:
  identifier: 'Cave 1'
  space: 'space1'
  cave: 'cave1'
  ko_glyphs: '!?"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz가나다라마바사아자차카타파하집무실유재석강호동이경규성시안녕세상고싶은말용신엽능점검표중롸예약'

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Name-Plate-1 Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# mqtt setup
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  on_message:
    - topic: "${space}/${cave}"
      then:
        - delay: 0.1s
        # - component.update: my_display
        # - display.page.show: page1
        - if:
            condition:
              lambda: 'return id(space1_cave1).state == "사용 가능";'
            then:
              - display.page.show: page2
              - component.update: my_display
        - if:
            condition:
              lambda: 'return id(space1_cave1).state.length() == 5;'
            then:
              - display.page.show: page5
              - component.update: my_display
            else:
              - display.page.show: page1
              - component.update: my_display
    - topic: "${space}/${cave}/reservation"
      then:
        - delay: 0.1s
        - display.page.show: page5
        - component.update: my_display
    - topic: "${space}/caveall"
      then:
        - delay: 0.1s
        - if:
            condition:
              lambda: 'return id(${space}_caveall).state == "사용 가능";'
            then:
              - display.page.show: page2
              - component.update: my_display
        - if:
            condition:
              lambda: 'return id(${space}_caveall).state == "점검중";'
            then:
              - display.page.show: page4
              - component.update: my_display
            else:
              - display.page.show: page3
              - component.update: my_display

# subscribe to topic published
text_sensor:
  - platform: mqtt_subscribe
    name: "${identifier}"
    id: "${space}_${cave}"
    topic: "${space}/${cave}"
  # - platform: mqtt_subscribe
  #   name: "${identifier} reservation"
  #   id: "${space}_${cave}_reservation"
  #   topic: "${space}/${cave}/reservation"
  - platform: mqtt_subscribe
    name: 'Cave all'
    id: space1_caveall
    topic: space1/caveall
  - platform: homeassistant
    id: "${space}_${cave}_time"
    entity_id: calendar.cave1_test
    attribute: start_time

# Example configuration entry
font:
  # - file: 'fonts/OpenSans-Regular.ttf'
  #   id: font1
  #   size: 35
  - file: 'fonts/NanumGothic-Regular.ttf'
    id: koNanum35
    size: 35
    glyphs: "${ko_glyphs}"
  - file: 'fonts/NanumGothic-Regular.ttf'
    id: koNanum20
    size: 20
    glyphs: "${ko_glyphs}"
  - file: 'fonts/NanumGothic-Regular.ttf'
    id: koNanum60
    size: 60
    glyphs: "${ko_glyphs}"

image:
  - file: 'images/wrench.png'
    id: my_image
    resize: 90x90

spi:
  clk_pin: D0
  mosi_pin: D1

display:
  - platform: waveshare_epaper
    cs_pin: D2 #2
    dc_pin: D6
    busy_pin: D7 #7
    reset_pin: D5
    model: 2.90inv2
    full_update_every: 0
    rotation: 90
    update_interval: never #30s #never #600s
    reset_duration: 1ms
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.print(0, 0, id(koNanum35), "집무실         $identifier");
          it.print(0, 50, id(koNanum20), "사용자: ");
          it.printf(90, 50, id(koNanum60), "%s", id(space1_cave1).state.c_str());
      - id: page2
        lambda: |-
          it.print(0, 0, id(koNanum35), "집무실         $identifier");
          it.printf(27, 50, id(koNanum60), "%s", id(space1_cave1).state.c_str());
      - id: page3
        lambda: |-
          it.printf(0, 40, id(koNanum35), "%s", id(space1_caveall).state.c_str());
      - id: page4
        lambda: |-
          it.image(0, 18, id(my_image));
          it.printf(100, 40, id(koNanum35), "%s", id(space1_caveall).state.c_str());
      - id: page5
        lambda: |-
          it.print(0, 0, id(koNanum35), "집무실         $identifier");
          it.print(80, 50, id(koNanum35), "사용 가능");
          it.printf(98, 100, id(koNanum20), "예약: %s", id(space1_cave1).state.c_str());